package com.lowbottgames.gpslogger.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lowbottgames.gpslogger.db.GPSData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GPSDATA".
*/
public class GPSDataDao extends AbstractDao<GPSData, Long> {

    public static final String TABLENAME = "GPSDATA";

    /**
     * Properties of entity GPSData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Time = new Property(1, Long.class, "time", false, "TIME");
        public final static Property Latitude = new Property(2, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, Double.class, "longitude", false, "LONGITUDE");
        public final static Property Provider = new Property(4, String.class, "provider", false, "PROVIDER");
        public final static Property Accuracy = new Property(5, Float.class, "accuracy", false, "ACCURACY");
        public final static Property Bearing = new Property(6, Float.class, "bearing", false, "BEARING");
        public final static Property Speed = new Property(7, Float.class, "speed", false, "SPEED");
        public final static Property Altitude = new Property(8, Double.class, "altitude", false, "ALTITUDE");
    };


    public GPSDataDao(DaoConfig config) {
        super(config);
    }
    
    public GPSDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GPSDATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TIME\" INTEGER," + // 1: time
                "\"LATITUDE\" REAL," + // 2: latitude
                "\"LONGITUDE\" REAL," + // 3: longitude
                "\"PROVIDER\" TEXT," + // 4: provider
                "\"ACCURACY\" REAL," + // 5: accuracy
                "\"BEARING\" REAL," + // 6: bearing
                "\"SPEED\" REAL," + // 7: speed
                "\"ALTITUDE\" REAL);"); // 8: altitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GPSDATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GPSData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(2, time);
        }
 
        Double latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(3, latitude);
        }
 
        Double longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(4, longitude);
        }
 
        String provider = entity.getProvider();
        if (provider != null) {
            stmt.bindString(5, provider);
        }
 
        Float accuracy = entity.getAccuracy();
        if (accuracy != null) {
            stmt.bindDouble(6, accuracy);
        }
 
        Float bearing = entity.getBearing();
        if (bearing != null) {
            stmt.bindDouble(7, bearing);
        }
 
        Float speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindDouble(8, speed);
        }
 
        Double altitude = entity.getAltitude();
        if (altitude != null) {
            stmt.bindDouble(9, altitude);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GPSData readEntity(Cursor cursor, int offset) {
        GPSData entity = new GPSData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // longitude
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // provider
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // accuracy
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6), // bearing
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // speed
            cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8) // altitude
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GPSData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setProvider(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAccuracy(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setBearing(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
        entity.setSpeed(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setAltitude(cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GPSData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GPSData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
