package com.lowbottgames.gpslogger.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GPSDATA".
 */
public class GPSData {

    private Long id;
    private Long time;
    private Double latitude;
    private Double longitude;
    private String provider;
    private Float accuracy;
    private Float bearing;
    private Float speed;
    private Double altitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GPSData() {
    }

    public GPSData(Long id) {
        this.id = id;
    }

    public GPSData(Long id, Long time, Double latitude, Double longitude, String provider, Float accuracy, Float bearing, Float speed, Double altitude) {
        this.id = id;
        this.time = time;
        this.latitude = latitude;
        this.longitude = longitude;
        this.provider = provider;
        this.accuracy = accuracy;
        this.bearing = bearing;
        this.speed = speed;
        this.altitude = altitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public Float getBearing() {
        return bearing;
    }

    public void setBearing(Float bearing) {
        this.bearing = bearing;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
